services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: resumeiq-api
    ports:
      - "8000:8000"
    environment:
      - RESUMEIQ_APP_ENV=docker
      - RESUMEIQ_DOCKER_MODE=true
      - RESUMEIQ_DATABASE_URL=sqlite:///./data/resumeiq.db
      - RESUMEIQ_LOG_LEVEL=INFO
      - RESUMEIQ_API_PORT=8000
      - RESUMEIQ_MLFLOW_TRACKING_URI=file:./mlruns
      - RESUMEIQ_MODEL_REGISTRY_PATH=artifacts/model_registry/model_registry.json
      - RESUMEIQ_EXTERNAL_GENAI_ENABLED=false
      - RESUMEIQ_GENAI_PROVIDER=none
    volumes:
      - resumeiq_data:/app/data

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: resumeiq-streamlit
    ports:
      - "8501:8501"
    environment:
      - RESUMEIQ_APP_ENV=docker
      - RESUMEIQ_DOCKER_MODE=true
      - RESUMEIQ_API_BASE_URL=http://api:8000
      - RESUMEIQ_DATABASE_URL=sqlite:///./data/resumeiq.db
      - RESUMEIQ_STREAMLIT_PORT=8501
      - RESUMEIQ_LOG_LEVEL=INFO
      - RESUMEIQ_EXTERNAL_GENAI_ENABLED=false
      - RESUMEIQ_GENAI_PROVIDER=none
    depends_on:
      - api
    volumes:
      - resumeiq_data:/app/data

volumes:
  resumeiq_data:
